name: Signal Bot (5m)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"   # yerleşik fetch var

      - name: Run signal job
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          # İstersen eşikleri burada override edebilirsin:
          # PCT_1S: "0.05"
          # VOL_MULT_15S: "1.2"
          # NO_HIT_SUMMARY: "1"
        run: node signal.js
